OBJ: visium_bc.h5ad
FILTERED_OBJ: visium_bc_filtered.h5ad 
ANALYSED_OBJ: visium_bc_analysed.h5ad
ANNOTATED_OBJ: visium_bc_annotated.h5ad
SPATIAL_DE_OBJ: visium_bc_annotated.h5ad


#FILTERING PARAMS 
#------------------
MIN_GENES: 50 
MIN_CELLS: 3

#MT PREFIX
#----------
MT: MT

#MARKER GENES
#-------------
MAKER_GENES: markers.txt 

#FIGURES
PREFIX: visium_bc

#ANNOTATIONS 
ANNOT_FILE: breast_visium_marker_reference.csv 
